export const GET_MOVIES_SUCCESS = 'GET_MOVIES_SUCCESS';
export const GET_MOVIE_SUCCESS = 'GET_MOVIE_SUCCESS';
export const ADD_MOVIE_SUCCESS = 'ADD_MOVIE_SUCCESS';
export const UPDATE_MOVIE_SUCCESS = 'UPDATE_MOVIE_SUCCESS';
export const DELETE_MOVIE_SUCCESS = 'DELETE_MOVIE_SUCCESS';
export const UNLOAD_MOVIE = 'UNLOAD_MOVIE';